### ISSUE TITLE
Notice : Undefined index

### ISSUE THREAD

**Issue by loorlab** [epayco/Plugin_ePayco_WooCommerce#1]
Saludos Amigos, en la pasarela de pagos está notificando las siguientes advertencias en WordPress :

Notice: Undefined index: description in /wp-content/plugins/woocommerce-payco-gateway/woocommerce-gateway-payco.php on line 45

Notice: Undefined index: POST in /wp-content/plugins/woocommerce-payco-gateway/woocommerce-gateway-payco.php on line 51

Muchas gracias !

**Comment by pruebasepayco** [comment]
Buenas tardes

Reciba un cordial saludo.

Informamos que se han realizado ajustes, mejoras y actualizaciones en el plugin, lo invitamos amablemente a realizar la actualización del plugin de acuerdo a la versión de woocommerce que presente, en caso de que ocurra algún inconveniente con el plugin, por favor informarnos.

Muchas gracias por su comprensión.

**Comment by loorlab** [comment]
> 
> 
> Buenas tardes
> 
> Reciba un cordial saludo.
> 
> Informamos que se han realizado ajustes, mejoras y actualizaciones en el plugin, lo invitamos amablemente a realizar la actualización del plugin de acuerdo a la versión de woocommerce que presente, en caso de que ocurra algún inconveniente con el plugin, por favor informarnos.
> 
> Muchas gracias por su comprensión.

Buen día Equipo ePayco , hay algo que nos desconcierta en la actualización del repositorio y agradecemos una aclaración.

La actualización del plugin la hacemos descargando de este repositorio o del repositorio en wordpress.org  https://es.wordpress.org/plugins/epayco-agregador-woocommerce/ ?

Por que hacemos esta pregunta ? Por que ni en wordpress.org ni aquí vemos una actualización del plugin y en github tampoco en su código encontramos actualizaciones excepto por el README.md (12 hours ago). - https://github.com/epayco/Plugin_ePayco_WooCommerce/compare/V4.0.x...master

Tampoco vemos ejecutado el PR --> https://github.com/epayco/Plugin_ePayco_WooCommerce/pulls .

Vamos a probar descargando la versión V4.0.x en nuestro sitio de pruebas  --> https://github.com/epayco/Plugin_ePayco_WooCommerce/releases  y cualquier error lo reportaremos aqui mismo.

Mil gracias !

**Comment by pruebasepayco** [comment]
Buenos dias,

Cordial saludo.

la actualización la pueden encontrar en la ruta:https://github.com/epayco/Plugin_ePayco_WooCommerce/releases/tag/V4.0.x, la documentación de el sitio oficial de wordpress en el momento no se ha realizado.

Agradecemos mucho los comentarios y las sugerencias que presentan, se tomaran en cuenta, por favor realizar las pruebas respectivas e informarnos si presentan algun inconveniente.

Muchas gracias por su comprensión, estaremos atentos.

**Comment by loorlab** [comment]
@pruebasepayco Realizamos el proceso de instalar : https://github.com/epayco/Plugin_ePayco_WooCommerce/releases/tag/V4.0.x y los warnings ya no se presentan activando el debug de WordPress.

Solo un detalle, el archivo woocommerce-gateway-payco.php tiene un problema de formato, tiene espacios en blanco que hace que el archivo tenga 3950 lineas de código.

Al retirar estos espacios debe quedar en 956 lineas de código, para que por favor lo revisen.

Mil gracias !
