### ISSUE TITLE
Pantalla negra al procesar pago

### ISSUE THREAD

**Issue by redesitos** [epayco/Plugin_ePayco_WooCommerce#21]
Cordial saludo.

El siguiente problema se presenta cuando un cliente realiza más de un clic sobre el botón de pagos, se ve la carga en la parte inferior de la url pero el sitio queda en pantalla completa lo que termina en transacción abandonada.

**Comment by JuanFelMesa** [comment]
@redesitos el inconveniente con el doble click al momento de dar click en pagar fue solucionado, esto no hace parte del plugin de woocommerce por lo cual no es necesario realizar una actualización, el error se presentaba era en nuestro script del checkout. 

Muchas gracias.
