### ISSUE TITLE
Divulgación de información sensible

### ISSUE THREAD

**Issue by duquejo01** [epayco/Plugin_ePayco_WooCommerce#6]
Durante de unas pruebas de seguridad se evidenció en el proceso de la pasarela de pagos una vulnerabilidad al **divulgar información sensible** del usuario en la URL.

El impacto es de un nivel **alto**, debido a que es posible acceder a información sensible del proceso que se está llevando a cabo en la plataforma.

![vulnerabilidad](https://user-images.githubusercontent.com/47703424/74982322-eca29580-5401-11ea-93b8-d34b925cee10.png)

Quedo atento a una pronta actualización de este issue.

**Comment by pruebasepayco** [comment]
Buenos días .

Reciba un cordial saludo.

Informamos que la información que establece en la imagen es la data de la transacción que ya internamente esta registrada en ePayco y en el módulo de woocomerce, por lo cual no representa ningún riesgo ya que la información que se regresa  no tiene valor alguno, son solo datos de facturación del cliente que ingresa en el formulario de woocommerce y el estado correspondiente del la transacción, solo sirve para registro en el módulo de órdenes de woocomerce con su estado inicial y se obtiene al redireccionamiento a la página de gracias, para el caso de confirmación es establecer el estado final de la orden y la información se envía por Post con una firma de seguridad la cual el plugin valida, por ende no habría inconveniente con el proceso de venta en woocomerce.

De igual forma se escalo el requerimiento  para una posible implementación al area encargada para que la redirección sea por Post y no por Get.

Muchas gracias, estaremos atentos a cualquier comentario.

**Comment by pruebasepayco** [comment]
Buenas tardes.

Reciba un cordial saludo.

Informamos que la información que recibe por GET es la información de facturacion que el cliente ingresa  en woocomerce para realizar el proceso de pago, esta información es retornada el momento de redireccionamiento a la página de gracias, si no requiere que esta información aparezca, por favor solicitamos crear un ticket de soporte a con este caso para evitar la información  retornada por get.

Ofrecemos disculpas por el inconveniente causado

**Comment by duquejo01** [comment]
Buenas tardes, se ha enviado el ticket,
Muchas gracias por la colaboración prestada.

**Comment by rvega** [comment]
Esto se solucionó? todavia pasa? por que no cierran este issue?

**Comment by duquejo01** [comment]
Hasta la fecha no han resuelto el ticket enviado. Todavía me encuentro esperando la solución a este issue...

**Comment by pruebasepayco** [comment]
Buenas noches.

Cordial saludo.

Por favor puedes confirmarnos el número del ticket, este lo puedes obtener de tu cuenta de epayco para validar en que estado esta este, informamos que este tipo de redireccion por get se puede configurar y omitir los datos, ya que algunos clientes utilizan algunas herramientas externas para hacer marketing con algunos datos que provienen del get, de igual forma este caso se escalo al area directiva donde validaran el caso a profundidad.

Ofrecemos disculpas por las demoras en responder a la solicitud, en  caso de que no tenga registro del ticket por favor solicitamos por medio del siguiente enlace reportar nuevamente este caso y si preferiblemente si es posible compartirnos accesos ftp con permisos solo a la carpeta del plugin de epayco, que se encuentra en la ruta, wp-config/plugins/ donde se realizara la configuración del requerimiento:
https://epayco.co/contacto/

**Comment by duquejo01** [comment]
Buenas noches,

Gracias por la pronta respuesta. El ticket creado para la solución de este Issue es el **#44355**.
El servidor maneja unos accesos restrictivos, por lo que, por temas de seguridad, no está permitido el acceso a personal externos. Sin embargo, podría realizar la configuración manual en el plugin, con la instrucción de ustedes.

Muchas gracias por la atención prestada.

**Comment by pruebasepayco** [comment]
Buenos dias.

Cordial saludo.

Perfecto, en el archivo de woocmmerce-gateway-payco.php, encontraras una función llamada ePayco_successful_request, dentro de esta finalizando debes de comentar el atributo:  $redirect_url = add_query_arg($arguments , $redirect_url );

Por favor realizar la prueba e informarnos,
Estaremos atentos.

**Comment by rvega** [comment]
Dónde? el último commit que veo en ese archivo es de febrero.

**Comment by pruebasepayco** [comment]
debes de tener en cuanta la versión de woocommerce para descargarte el plugin compatible, : confirmo en la ruta ep-config/plugins/ el nombre del plugin de epayco de acuerdo a laversion/ woocmmerce-gateway-payco.php

, encontraras una función llamada ePayco_successful_request, dentro de esta finalizando debes de comentar el atributo: $redirect_url = add_query_arg($arguments , $redirect_url );

Por favor realizar la prueba e informarnos,
Estaremos atentos.

**Comment by rvega** [comment]
Gracias por responder rapidamente. Pero sigo con la misma pregunta: En el repositorio se ve que la ultima modificación fué hace 2 meses:
https://github.com/epayco/Plugin_ePayco_WooCommerce/branches/all

Dónde están las versiones que mencionas?

Gracias!

**Comment by pruebasepayco** [comment]
Buenos dias cordial saludo:

en el siguiente enlace encontraras el readme con las diferentes versiones del plugin
https://github.com/epayco/Plugin_ePayco_WooCommerce
debes de descargarte la versión más compatible con el woocomemrce que tienes, una vez lo instales desde el cpanel o ftp ingresas a las rutas que anteriormente se ha mencionado y sobre la funcion:ePayco_successful_request debes de comentar la siguiente variable:  
$redirect_url = add_query_arg($arguments , $redirect_url );

si presentas inconveniente por favor agendar en el siguiente link una reunión con el equipo de soporte: https://calendly.com/epayco

Muchas gracias por su comprension.

**Comment by rvega** [comment]
Entendido, gracias.
Rafael Vega.
