### ISSUE TITLE
Ejemplo de pagina de respuesta

### ISSUE THREAD

**Issue by marioserrano09** [epayco/Plugin_ePayco_WooCommerce#7]
Hola, ¿donde puedo encontrar un ejemplo de página de respuesta de ejemplo de pago con woocommerce? La idea es que muestre el estado del pago y no solo un  mensaje estático. Gracias

**Comment by camilolunacom** [comment]
Hola @marioserrano09, después de no encontrar ejemplos revisé el código del plugin y si no se define ninguna página se usa la de WooCommerce por defecto, así que eso sería lo recomendado.

**Comment by djcesar** [comment]
Srs buenas noches ustedes como dejan seteado en epayco?

![image](https://user-images.githubusercontent.com/5298553/79628503-2abcec80-8107-11ea-8508-75e824c835b5.png)

 lo dejan sin urls ahí? cual es la practica recomendada?

**Comment by camilolunacom** [comment]
@djcesar correcto, queda sin seleccionar nada:

![image](https://user-images.githubusercontent.com/5571281/79642987-3986bc00-8166-11ea-93af-676bc9eba0b6.png)
